name: aws-lambda-haskell-error
version: 0.1.0.0
github: "jonathanlorimer/aws-lambda-haskell-error"
license: BSD3
author: "Jonathan Lorimer"
maintainer: "jonathan_lorimer@mac.com"
copyright: "2019 Jonathan Lorimer"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ecobee/smartbuildings-sensor-lookup-sync#readme>

dependencies:
  - aeson
  - aws-lambda-haskell-runtime >= 2.0.0
  - base >= 4.7 && < 5
  - bson
  - containers
  - http-conduit
  - monad-logger
  - mtl
  - mongoDB
  - persistent
  - persistent-mysql
  - persistent-template
  - text
  - time

library:
  source-dirs: src

executables:
  bootstrap:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aws-lambda-haskell-error

tests:
  aws-lambda-haskell-error-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aws-lambda-haskell-error

default-extensions:
  - TemplateHaskell
  - RecordWildCards
  - OverloadedStrings
  - DeriveGeneric
